name: CI/CD Demo

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: [ self-hosted, Linux, X64 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & test backend
        run: |
          echo "No tests to run"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
      - name: Debug Docker login in CI
        run: |
          set -x
          echo ">>> USER: ${{ secrets.DOCKERHUB_USER }}"
          echo ">>> TOKEN LEN: ${#{{ secrets.DOCKERHUB_TOKEN }}} (should be >0)"
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: a9722399100/k8s-cicd-demo-backend:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: [ self-hosted, Linux, X64 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
