name: CI/CD Demo

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: [ self-hosted, Linux, X64 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          registry: docker.io
          context: ./backend
          push: true
          tags: |
            docker.io/a9722399100/k8s-cicd-demo-backend:${{ github.sha }}
            docker.io/a9722399100/k8s-cicd-demo-backend:latest

  deploy:
    needs: build-and-push
    runs-on: [ self-hosted, Linux, X64 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
